### ISSUE TITLE
I have passed -key,-to,-from，but len(flag.Args) == 0

### ISSUE THREAD

**Issue by foolishway** [robpike/translate#2]

**Comment by robpike** [comment]
Without more information there's nothing I can do to help. Perhaps you're not using it correctly? I have $GOOGLEAPIKEY exported by my .bashrc. See also https://translatepress.com/docs/automatic-translation/generate-google-api-key/

```
% translate maison
House (fr)
% translate -to de maison
Haus (fr)
% translate -from fr -to de maison
Haus ()
% 

```

**Comment by foolishway** [comment]
Mr Rob, I am so lucky to have your reply. It's my fault, I have used uncorrectly.
